import { NextResponse } from "next/server";
import { adminDb } from "@/lib/firebase-admin";

const DEFAULT_FAQ = [
  { id: "faq_1",  ordre: 1,  active: true, question: "Combien de temps prend la conception de mon application?", reponse: "La conception et le déploiement de votre application prennent environ 8 semaines de la signature du contrat jusqu'au lancement. Ce délai inclut le design, le développement, les tests, la rencontre de validation, la soumission sur les stores et la formation. Vous pouvez suivre l'avancement en temps réel dans votre feuille de route. Si tout se passe bien, il n'est pas rare que nous livrions avant ce délai." },
  { id: "faq_2",  ordre: 2,  active: true, question: "Comment puis-je suivre l'avancement de mon application?", reponse: "Votre feuille de route, accessible depuis votre portail, vous permet de suivre chaque étape du déploiement en temps réel. Vous y verrez le statut de chaque étape, la date de lancement estimée et le journal de développement où notre équipe publie des mises à jour avec captures d'écran au fur et à mesure de la conception. Vous recevrez également un courriel à chaque étape importante complétée." },
  { id: "faq_3",  ordre: 3,  active: true, question: "Que se passe-t-il après avoir complété le formulaire de branding?", reponse: "Dès que vous avez complété et soumis votre formulaire de branding, notre équipe reçoit une notification et débute l'analyse de vos informations. Vous recevrez un message de confirmation dans votre portail. Par la suite, nous passons à l'étape de design où nous concevons les écrans de votre application selon vos couleurs, votre logo et vos templates choisis. Vous serez informé dès que cette étape sera complétée." },
  { id: "faq_4",  ordre: 4,  active: true, question: "Puis-je modifier mes informations de branding après les avoir soumises?", reponse: "Oui, vous pouvez retourner dans la section Branding de votre portail à tout moment pour modifier vos informations. Cependant, si votre application est déjà en cours de développement, certaines modifications pourraient entraîner des délais supplémentaires. Nous vous recommandons de nous contacter via la messagerie du portail avant de faire des changements importants afin qu'on puisse vous guider sur l'impact de ces modifications." },
  { id: "faq_5",  ordre: 5,  active: true, question: "Comment fonctionne la rencontre de validation?", reponse: "Une fois le développement de votre application terminé, notre équipe vous proposera trois plages horaires disponibles directement dans votre portail. Vous n'aurez qu'à choisir celle qui vous convient le mieux. La rencontre se déroule en vidéo, nous vous présentons l'application complète et vous nous faites part de vos commentaires et de ce que vous souhaitez ajuster avant le lancement. Suite à cette rencontre, nous apportons les modifications nécessaires avant de procéder aux tests finaux et à la soumission sur les stores." },
  { id: "faq_6",  ordre: 6,  active: true, question: "Comment les points sont-ils attribués à mes clients?", reponse: "Les points sont attribués à chaque visite lors de la validation de la facture par un employé. Selon votre configuration, un certain nombre de points est accordé par dollar dépensé. Par exemple, si votre programme est configuré à 5 points par dollar et qu'un client dépense 20$, il reçoit 100 points. La validation se fait soit via un iPad en succursale, soit via une liaison avec votre système POS, selon la méthode choisie lors de la configuration." },
  { id: "faq_7",  ordre: 7,  active: true, question: "Mes clients peuvent-ils perdre leurs points?", reponse: "Non, les points accumulés par vos clients n'expirent jamais et ne peuvent pas être retirés. Une fois gagnés, ils restent dans le compte du membre jusqu'à ce qu'il les échange contre une récompense. C'est un avantage important de notre programme, vos clients peuvent accumuler à leur rythme sans crainte de perdre ce qu'ils ont gagné." },
  { id: "faq_8",  ordre: 8,  active: true, question: "Est-ce que je peux modifier les récompenses après le lancement de l'app?", reponse: "Oui, vous pouvez modifier, ajouter ou retirer des récompenses à tout moment directement depuis le tableau de bord administrateur de votre application. Ces changements sont appliqués en temps réel et vos membres verront immédiatement les nouvelles récompenses disponibles." },
  { id: "faq_9",  ordre: 9,  active: true, question: "Comment un client réclame-t-il une récompense?", reponse: "Depuis l'application, le client accède à la section Récompenses et sélectionne la récompense qu'il souhaite échanger. Il génère ensuite un code de réclamation ou un QR code qu'il présente à l'employé en succursale. L'employé valide la réclamation depuis le tableau de bord administrateur et remet la récompense au client. Les points sont automatiquement déduits du solde du membre." },
  { id: "faq_12", ordre: 12, active: true, question: "Est-ce que tous mes clients peuvent jouer au bonus chaque jour?", reponse: "Oui, tous les membres inscrits à votre application peuvent jouer au bonus quotidien une fois par jour. La disponibilité du bonus se renouvelle automatiquement chaque jour à minuit. Il n'y a aucune limite au nombre de membres qui peuvent y participer simultanément." },
  { id: "faq_13", ordre: 13, active: true, question: "Puis-je modifier les gains du bonus?", reponse: "Les gains du bonus quotidien sont configurés par notre équipe selon une distribution équilibrée. Habituellement, les gains sont répartis comme suit : 15 pts (environ 60% des tirages), 25 pts (environ 30%), 50 pts (environ 5%), 100 pts (environ 3%), 250 pts (environ 1%), 500 pts (environ 0,5%) et 1000 pts (moins de 0,5%). Si vous souhaitez ajuster ces pourcentages, contactez-nous et nous évaluerons les modifications avec vous." },
  { id: "faq_14", ordre: 14, active: true, question: "Comment mes employés ajoutent-ils des points à un client?", reponse: "La méthode de validation dépend de la configuration choisie lors de votre mise en place. Dans la plupart des cas, l'employé accède au tableau de bord administrateur sur un iPad en succursale, scanne le code-barres ou le QR code du client depuis l'application, entre le montant de la facture et confirme. Les points sont attribués automatiquement et instantanément au compte du membre." },
  { id: "faq_15", ordre: 15, active: true, question: "Que se passe-t-il si un employé oublie de valider une facture?", reponse: "Si un employé oublie de valider une facture au moment de la transaction, il est possible de le faire manuellement après coup depuis le tableau de bord administrateur. Un document de formation présentera la façon de procéder selon votre application. Nous recommandons de former vos employés dès le départ pour minimiser les oublis, car une validation systématique est essentielle à la satisfaction de vos membres." },
  { id: "faq_16", ordre: 16, active: true, question: "Mon POS est-il compatible avec l'application?", reponse: "Nous tentons d'établir une liaison avec votre système POS peu importe le système que vous utilisez. La compatibilité dépend des capacités techniques de votre POS et sera évaluée lors de la mise en place. Si une intégration directe n'est pas possible, la validation peut aussi se faire via un iPad en succursale sans aucune intégration requise. Contactez-nous pour discuter de votre situation spécifique." },
  { id: "faq_17", ordre: 17, active: true, question: "Puis-je avoir plusieurs iPads en succursale?", reponse: "Oui, vous pouvez utiliser autant d'iPads que nécessaire en succursale. Chaque appareil se connecte au même tableau de bord administrateur et toutes les transactions sont centralisées. C'est particulièrement utile pour les restaurants à fort achalandage où plusieurs caisses opèrent simultanément." },
  { id: "faq_18", ordre: 18, active: true, question: "Comment puis-je mettre à jour ma méthode de paiement?", reponse: "Vous pouvez mettre à jour votre méthode de paiement à tout moment depuis la section Paiement de votre portail. Cliquez sur Gérer ma carte et suivez les étapes pour ajouter ou remplacer votre carte de crédit. Le changement est appliqué immédiatement et sera utilisé pour votre prochain prélèvement mensuel." },
  { id: "faq_19", ordre: 19, active: true, question: "Quand suis-je facturé chaque mois?", reponse: "La facturation débute la majorité du temps à la date de lancement de votre application, puis le même jour chaque mois par la suite. Votre prochaine date de facturation est toujours visible dans la section Paiement de votre portail." },
  { id: "faq_20", ordre: 20, active: true, question: "Puis-je annuler mon abonnement?", reponse: "Les conditions d'annulation sont définies dans votre contrat et peuvent varier selon votre entente. Nous vous recommandons de consulter votre contrat pour connaître les conditions spécifiques qui s'appliquent à votre situation. Pour toute question, contactez-nous directement et il nous fera plaisir de vous guider." },
  { id: "faq_21", ordre: 21, active: true, question: "Puis-je ajouter des succursales à mon forfait?", reponse: "Oui, il est possible d'ajouter des succursales à votre forfait à tout moment. Chaque succursale supplémentaire est facturée selon la grille tarifaire en vigueur. Contactez-nous pour connaître les tarifs et procéder à l'ajout." },
  { id: "faq_22", ordre: 22, active: true, question: "Quelle est la différence entre le forfait Essentiel et Prestige?", reponse: "Le forfait Essentiel inclut tout ce qu'il faut pour lancer et gérer votre programme de fidélité, votre application mobile complète, le programme de points, les récompenses, le bonus quotidien, les promotions et le tableau de bord administrateur. Le forfait Prestige ajoute des fonctionnalités avancées de CRM et de segmentation clientèle, des alertes automatisées selon le comportement de vos membres, un rapport de performance mensuel avec analyse, des tableaux analytiques 7/30/90 jours et une rencontre stratégique mensuelle avec notre équipe. Si vous souhaitez faire passer votre programme au niveau supérieur et utiliser les données pour prendre des décisions stratégiques, le Prestige est fait pour vous." },
  { id: "faq_23", ordre: 23, active: true, question: "Comment puis-je contacter l'équipe AW Solution?", reponse: "Vous pouvez nous contacter directement via la messagerie de votre portail, par courriel ou par téléphone. Nos coordonnées sont disponibles dans la section Support de votre portail. Nous nous engageons à vous répondre dans les plus brefs délais." },
  { id: "faq_24", ordre: 24, active: true, question: "Puis-je demander des modifications à mon application après le lancement?", reponse: "Oui, des modifications peuvent être apportées à votre application après le lancement. Certaines modifications mineures comme l'ajout de récompenses ou la création de promotions se font directement depuis votre tableau de bord administrateur. Pour des modifications plus importantes touchant au design ou aux fonctionnalités, contactez-nous via la messagerie du portail et nous évaluerons la demande avec vous." },
  { id: "faq_25", ordre: 25, active: true, question: "Que faire si un client a un problème avec l'application?", reponse: "Si un de vos membres rencontre un problème avec l'application, vous pouvez nous en informer via la messagerie de votre portail ou directement par courriel ou téléphone. Décrivez le problème le plus précisément possible, idéalement avec une capture d'écran, et notre équipe prendra en charge la situation dans les plus brefs délais." },
  { id: "faq_26", ordre: 26, active: true, question: "Comment puis-je mettre à jour les informations de mon restaurant dans l'app?", reponse: "Les informations de base de votre restaurant visibles dans l'application sont configurées lors de la mise en place initiale. Pour les modifier, contactez-nous via la messagerie de votre portail en nous indiquant les changements souhaités et notre équipe s'occupera de les appliquer." },
];

export async function POST() {
  try {
    const ref  = adminDb.doc("admin_config/faq");
    const snap = await ref.get();
    if (snap.exists && snap.data()?.initialized === true) {
      return NextResponse.json({ ok: true, seeded: false });
    }
    await ref.set({ initialized: true, questions: DEFAULT_FAQ });
    return NextResponse.json({ ok: true, seeded: true });
  } catch (err) {
    console.error("[faq seed]", err);
    return NextResponse.json({ error: "Erreur" }, { status: 500 });
  }
}
